# Generated by Django 5.2.16 on 2026-07-25 12:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("docx", "DOCX"),
                            ("xlsx", "XLSX"),
                            ("google_sheet", "Google Sheet snapshot"),
                            ("hal_api", "HAL API snapshot"),
                            ("manual", "Manual"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_name", models.CharField(max_length=500)),
                ("stored_file", models.CharField(max_length=1000)),
                ("file_sha256", models.CharField(max_length=64, unique=True)),
                ("parser_version", models.CharField(max_length=80)),
                ("report_sha256", models.CharField(max_length=64)),
                ("record_count", models.PositiveIntegerField()),
                ("report", models.JSONField(default=dict)),
                ("retrieved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-retrieved_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("before_checksum", models.CharField(blank=True, max_length=64)),
                ("after_checksum", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("publication_key", models.CharField(max_length=80, unique=True)),
                ("publication_type", models.CharField(max_length=40)),
                ("hal_document_type", models.CharField(blank=True, max_length=20)),
                ("title", models.TextField()),
                (
                    "publication_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=16)),
                ("pages", models.CharField(blank=True, max_length=80)),
                ("authors", models.JSONField(default=list)),
                ("editors", models.JSONField(default=list)),
                ("journal_title", models.TextField(blank=True)),
                ("book_title", models.TextField(blank=True)),
                ("publisher", models.TextField(blank=True)),
                ("publisher_city", models.CharField(blank=True, max_length=200)),
                ("volume", models.CharField(blank=True, max_length=80)),
                ("issue", models.CharField(blank=True, max_length=80)),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("isbn", models.JSONField(default=list)),
                ("issn", models.JSONField(default=list)),
                ("conference_title", models.TextField(blank=True)),
                (
                    "conference_start_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "conference_end_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "conference_city",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "conference_country",
                    models.CharField(blank=True, max_length=200),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("blocked", "Blocked"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "readiness_state",
                    models.CharField(
                        choices=[
                            ("parsed", "Parsed"),
                            ("needs_enrichment", "Needs enrichment"),
                            ("needs_review", "Needs review"),
                            ("hal_ready", "HAL ready"),
                            ("preprod_validated", "Preproduction validated"),
                            ("production_submitted", "Production submitted"),
                        ],
                        default="parsed",
                        max_length=32,
                    ),
                ),
                ("missing_required_fields", models.JSONField(default=list)),
                ("hal_status", models.CharField(blank=True, max_length=40)),
                ("hal_id", models.CharField(blank=True, max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "indexes": [
                    models.Index(
                        fields=["publication_type"],
                        name="catalog_pub_publica_57b8f8_idx",
                    ),
                    models.Index(
                        fields=["readiness_state"],
                        name="catalog_pub_readine_7f38a7_idx",
                    ),
                    models.Index(
                        fields=["hal_status"],
                        name="catalog_pub_hal_sta_65d00a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("locator", models.CharField(max_length=200)),
                ("original_citation", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("record_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_records",
                        to="catalog.publication",
                    ),
                ),
                (
                    "source_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="catalog.sourceimport",
                    ),
                ),
            ],
            options={"ordering": ["source_import__retrieved_at", "locator"]},
        ),
        migrations.CreateModel(
            name="FieldAssertion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_path", models.CharField(max_length=200)),
                ("value", models.JSONField()),
                ("normalized_value", models.TextField(blank=True)),
                ("origin", models.CharField(max_length=40)),
                ("confidence", models.CharField(blank=True, max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assertions",
                        to="catalog.publication",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assertions",
                        to="catalog.sourcerecord",
                    ),
                ),
            ],
            options={"ordering": ["field_path", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="sourcerecord",
            constraint=models.UniqueConstraint(
                fields=("source_import", "locator"),
                name="unique_source_import_locator",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldassertion",
            index=models.Index(
                fields=["publication", "field_path", "state"],
                name="catalog_fie_publica_ecae32_idx",
            ),
        ),
    ]
