# Generated by Django 5.2.16 on 2026-07-25 14:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "permissions": [
                    (
                        "review_publication",
                        "Can accept or reject proposed field changes",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssertionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_path", models.CharField(max_length=200)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("base_version", models.PositiveIntegerField()),
                ("resulting_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_assertion_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assertion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="catalog.fieldassertion",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="catalog.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["publication", "-created_at"],
                        name="catalog_ass_publica_a46ec4_idx",
                    )
                ],
            },
        ),
    ]
