# Generated by Django 5.2.16 on 2026-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_publication_options_assertiondecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="assertiondecision",
            name="applied_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assertiondecision",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("edited", "Edited"),
                ],
                max_length=20,
            ),
        ),
    ]
