# Generated by Django 5.2.16 on 2026-07-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_assertiondecision_applied_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "permissions": [
                    (
                        "review_publication",
                        "Peut accepter ou rejeter les modifications de champs proposées",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="assertiondecision",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepté"),
                    ("rejected", "Rejeté"),
                    ("edited", "Modifié"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fieldassertion",
            name="state",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposé"),
                    ("accepted", "Accepté"),
                    ("rejected", "Rejeté"),
                    ("superseded", "Remplacé"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="readiness_state",
            field=models.CharField(
                choices=[
                    ("parsed", "Analysé"),
                    ("needs_enrichment", "À enrichir"),
                    ("needs_review", "À vérifier"),
                    ("hal_ready", "Prêt pour HAL"),
                    ("preprod_validated", "Validé en préproduction"),
                    ("production_submitted", "Soumis en production"),
                ],
                default="parsed",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="review_state",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("needs_review", "À vérifier"),
                    ("approved", "Approuvé"),
                    ("blocked", "Bloqué"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="sourceimport",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("docx", "DOCX"),
                    ("xlsx", "XLSX"),
                    ("google_sheet", "Instantané Google Sheet"),
                    ("hal_api", "Instantané API HAL"),
                    ("manual", "Manuel"),
                ],
                max_length=24,
            ),
        ),
    ]
