# Generated by Django 5.2.16 on 2026-07-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_publication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assertiondecision",
            name="previous_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assertiondecision",
            name="assertion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decision",
                to="catalog.fieldassertion",
            ),
        ),
    ]
