# Generated by Django 5.2.16 on 2026-08-03 20:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_assertiondecision_previous_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSummaryCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_sha256", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=100)),
                ("generator_version", models.CharField(max_length=80)),
                ("abstract_en", models.TextField()),
                ("abstract_fr", models.TextField()),
                ("keywords_en", models.JSONField(default=list)),
                ("keywords_fr", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_sha256", "model_name", "generator_version"),
                        name="unique_document_summary_generation",
                    )
                ],
            },
        ),
    ]
