# Generated by Django 5.2.16 on 2026-08-03 21:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalog", "0006_documentsummarycache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveDocumentSummaryGeneration",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="active_document_summary_generation",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSummaryGenerationAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_sha256", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.RemoveConstraint(
            model_name="documentsummarycache",
            name="unique_document_summary_generation",
        ),
        migrations.AddField(
            model_name="documentsummarycache",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_summary_cache_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsummarycache",
            constraint=models.UniqueConstraint(
                fields=("owner", "document_sha256", "model_name", "generator_version"),
                name="unique_user_document_summary_generation",
            ),
        ),
        migrations.AddField(
            model_name="documentsummarygenerationattempt",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_summary_generation_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="documentsummarygenerationattempt",
            index=models.Index(
                fields=["owner", "created_at"], name="catalog_doc_owner_i_fb9a45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsummarygenerationattempt",
            index=models.Index(
                fields=["created_at"], name="catalog_doc_created_bfcfff_idx"
            ),
        ),
    ]
