# Generated by Django 5.2.16 on 2026-08-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_activedocumentsummarygeneration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsummarycache",
            name="document_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="documentsummarycache",
            name="source_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
