# Generated by Django 5.2.16 on 2026-08-08 21:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_documentsummarycache_document_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsummarycache",
            name="source_file",
            field=models.FileField(blank=True, upload_to="document-sources/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="documentsummarycache",
            name="suggested_authors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="documentsummarycache",
            name="suggested_doi",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="documentsummarycache",
            name="suggested_publication_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="documentsummarycache",
            name="suggested_publication_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DocumentPublicationLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("linked", "Notice existante"),
                            ("created", "Nouveau brouillon local"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_publication_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_links",
                        to="catalog.publication",
                    ),
                ),
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_link",
                        to="catalog.documentsummarycache",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
