# Generated by Django 5.2.16 on 2026-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_documentsummarycache_source_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="abstract_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="abstract_fr",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="keywords_en",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="publication",
            name="keywords_fr",
            field=models.JSONField(default=list),
        ),
    ]
