# Generated by Django 5.2.16 on 2026-08-09 16:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_publication_abstract_en_publication_abstract_fr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "permissions": [
                    (
                        "review_publication",
                        "Peut accepter ou rejeter les modifications de champs proposées",
                    ),
                    (
                        "submit_hal_preprod",
                        "Peut valider une nouvelle notice dans HAL préproduction",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HALOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("publication_version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "Prêt à confirmer"),
                            ("submitting", "Envoi en cours"),
                            ("accepted", "Accepté en préproduction"),
                            ("rejected", "Refusé en préproduction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duplicate_check", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_operations",
                        to="catalog.publication",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_hal_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="HALPayload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("environment", models.CharField(default="preprod", max_length=20)),
                ("content", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("validation_errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payload",
                        to="catalog.haloperation",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="HALSubmissionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("environment", models.CharField(default="preprod", max_length=20)),
                ("test_mode", models.BooleanField(default=True)),
                ("endpoint", models.URLField(max_length=500)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("returned_hal_id", models.CharField(blank=True, max_length=80)),
                ("returned_hal_url", models.URLField(blank=True, max_length=1000)),
                ("response_body", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="catalog.haloperation",
                    ),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="catalog.halpayload",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_submission_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.AddIndex(
            model_name="haloperation",
            index=models.Index(
                fields=["publication", "-created_at"],
                name="catalog_hal_publica_d19183_idx",
            ),
        ),
    ]
