# Generated by Django 5.2.16 on 2026-08-09 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_publication_options_haloperation_halpayload_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="halpayload",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment", "preprod")),
                name="hal_payload_preprod_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="halsubmissionattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment", "preprod"), ("test_mode", True)),
                name="hal_attempt_preprod_test_only",
            ),
        ),
    ]
