# Generated by Django 5.2.16 on 2026-08-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_publication_hal_synced_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldassertion",
            name="document_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="field_assertions",
                to="catalog.documentsummarycache",
            ),
        ),
        migrations.AlterField(
            model_name="fieldassertion",
            name="source_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assertions",
                to="catalog.sourcerecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldassertion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("document_summary__isnull", True),
                        ("source_record__isnull", False),
                    ),
                    models.Q(
                        ("document_summary__isnull", False),
                        ("source_record__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="field_assertion_has_exactly_one_source",
            ),
        ),
    ]
