# Generated by Django 5.2.16 on 2026-08-11 21:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_halcredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "permissions": [
                    (
                        "review_publication",
                        "Peut accepter ou rejeter les modifications de champs proposées",
                    ),
                    (
                        "submit_hal_preprod",
                        "Peut valider une nouvelle notice dans HAL préproduction",
                    ),
                    (
                        "submit_hal_production",
                        "Peut déposer une nouvelle notice dans HAL production",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HALProductionDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("publication_version", models.PositiveIntegerField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("duplicate_check", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "Prêt à confirmer"),
                            ("submitting", "Dépôt en cours"),
                            ("accepted", "Accepté par HAL"),
                            ("rejected", "Refusé par HAL"),
                            ("uncertain", "Résultat à vérifier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preprod_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_deposit",
                        to="catalog.haloperation",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_production_deposits",
                        to="catalog.publication",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_hal_production_deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="HALProductionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField(max_length=500)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("returned_hal_id", models.CharField(blank=True, max_length=80)),
                ("returned_hal_url", models.URLField(blank=True, max_length=1000)),
                ("response_body", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_attempts",
                        to="catalog.halpayload",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_production_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deposit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt",
                        to="catalog.halproductiondeposit",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
