# Generated by Django 5.2.16 on 2026-08-13 20:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_publication_options_halproductiondeposit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HALRemovalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("former_hal_id", models.CharField(max_length=80)),
                ("former_hal_status", models.CharField(blank=True, max_length=40)),
                ("reason", models.TextField()),
                (
                    "confirmation_method",
                    models.CharField(default="manual_hal_interface", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_removal_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_removal_records",
                        to="catalog.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publication", "former_hal_id"),
                        name="unique_publication_former_hal_id",
                    )
                ],
            },
        ),
    ]
