# Generated by Django 5.2.16 on 2026-08-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_halremovalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="journal_hal_id",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
