# Generated by Django 5.2.16 on 2026-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_userinterfacepreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterfacepreference",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatique — langue du navigateur"),
                    ("fr", "Français"),
                    ("en", "English"),
                ],
                max_length=2,
            ),
        ),
    ]
