# Generated by Django 5.2.16 on 2026-09-12 14:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_userinterfacepreference_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "permissions": [
                    (
                        "review_publication",
                        "Peut accepter ou rejeter les modifications de champs proposées",
                    ),
                    (
                        "submit_hal_preprod",
                        "Peut valider une nouvelle notice dans HAL préproduction",
                    ),
                    (
                        "submit_hal_production",
                        "Peut déposer une nouvelle notice dans HAL production",
                    ),
                    (
                        "update_hal_production",
                        "Peut mettre à jour une notice existante sur HAL production",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HALUpdateOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("publication_version", models.PositiveIntegerField()),
                ("hal_id", models.CharField(max_length=80)),
                ("hal_document_version", models.PositiveIntegerField()),
                ("payload_content", models.TextField()),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("prepared", "Prêt pour le test"),
                            ("test_accepted", "Test accepté"),
                            ("submitting", "Mise à jour en cours"),
                            ("accepted", "Acceptée par HAL"),
                            ("rejected", "Refusée par HAL"),
                            ("uncertain", "Résultat à vérifier"),
                        ],
                        default="prepared",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_update_operations",
                        to="catalog.publication",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_hal_update_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="HALUpdateAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_mode", models.BooleanField(default=True)),
                ("target_url", models.URLField(max_length=500)),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("returned_hal_id", models.CharField(blank=True, max_length=80)),
                ("returned_hal_url", models.URLField(blank=True, max_length=1000)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hal_update_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="catalog.halupdateoperation",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.AddIndex(
            model_name="halupdateoperation",
            index=models.Index(
                fields=["publication", "-created_at"],
                name="catalog_hal_publica_b497dd_idx",
            ),
        ),
    ]
