# Generated by Django 5.2.16 on 2026-09-12 14:31

from django.db import migrations

# Permission names are stored on auth.Permission rows at creation time and
# are not reliably renamed by post_migrate when Meta.permissions changes, so
# existing rows (created with the earlier French names) are updated here.
ENGLISH_PERMISSION_NAMES = {
    "review_publication": "Can accept or reject proposed field changes",
    "submit_hal_preprod": "Can validate a new record in HAL pre-production",
    "submit_hal_production": "Can submit a new record to HAL production",
    "update_hal_production": "Can update an existing record on HAL production",
}


def rename_permissions_to_english(apps, schema_editor):
    permission_model = apps.get_model("auth", "Permission")
    for codename, name in ENGLISH_PERMISSION_NAMES.items():
        permission_model.objects.filter(
            codename=codename, content_type__app_label="catalog"
        ).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_alter_publication_options_halupdateoperation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-publication_year", "title", "publication_key"],
                "permissions": [
                    (
                        "review_publication",
                        "Can accept or reject proposed field changes",
                    ),
                    (
                        "submit_hal_preprod",
                        "Can validate a new record in HAL pre-production",
                    ),
                    (
                        "submit_hal_production",
                        "Can submit a new record to HAL production",
                    ),
                    (
                        "update_hal_production",
                        "Can update an existing record on HAL production",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            rename_permissions_to_english, migrations.RunPython.noop
        ),
    ]
